server:
  port: 8080

ldap:
  url: ldap://localhost
  port: 389
  domain: schloss-gaienhofen.email
  root: dc=schloss-gaienhofen,dc=email
  managerDn: event-manager@schloss-gaienhofen.email
  managerPassword: Gai-EM-9268%

spring:

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:project;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: root
    password: ""

  ldap:
    embedded:
      ldif: classpath:test-schema.ldif
      port: 389
      validation:
        enabled: false
      base-dn: dc=schloss-gaienhofen,dc=email

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
