server:
  port: 8080

ldap:
  url: ldap://gpd-srv-dc01.schloss-gaienhofen.email
  port: 389
  managerDn: event-manager@schloss-gaienhofen.email
  managerPassword: Gai-EM-9268%

spring:

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/eventapp
    username: eventapp-admin
    password: admin@2019!
  mail:
    host: localhost
    port: 2525
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
