server:
  port: 8080

ldap:
  url: ldap://gpd-srv-dc01.schloss-gaienhofen.email
  port: 389
#  managerDn: XXX        # defined by -D param in service
#  managerPassword: XXX  # defined by -D param in service

spring:

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/eventapp
    username: eventapp-admin
#    password: XXX  # defined by -D param in service
  mail:
    host: localhost
    port: 25
    username: noreply@schloss-gaienhofen.email
    password:
    properties:
      mail:
        smtp:
          auth: false
          tls: false
          starttls:
            enable: false
